number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ "
lang_char: 'abcdefghijklmnopqrstuvwxyzABCDEFGHIJKLMNOPQRSTUVWXYZЁЂЄІЇЈЉЊЋЎЏАБВГДЕЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдежзийклмнопрстуфхцчшщъыьэюяёђєіїјљњћўџҐґҮүө'
experiment_name: 'cyrillic_g1_ft'
train_data: False
valid_data: False
valid_items_count: 1000
status_every_batch: 8
#Text generator options tg_*
#tg_distributed: "172.25.0.86:50051"
tg_distributed: False
tg_dbg_server: False
tg_settings:
  filter_chars: "'|`$*\\\"/;@_~%&#"
  generators:
    - rnd
    - en
    - ru
  length: 3
  augs:
    allow_list:
      - blur
      - motion_blur
      - downsample
      - jpeg_artifact
      - noise
      - sin_cos
      #- none
    # number of simultanious augmentations
    k: 1
    # Image, Noise, Plain probabilities
    inp_weights:
      - 0.33
      - 0.33
      - 0.33
    text_blur: 4
    text_blur_rnd: True
    blur: 4
    blur_rnd: True
    downsample_factor: 4
    jpeg_artifact_q: 14
    motion_blur_sz_min: 10
    motion_blur_sz_max: 15
    noise_mean: 1
    noise_stddev: 0.3
    invert_chance: 0.5
    overexposure_chance: 0.0
    overexposure_k: 1
manualSeed: 1111
workers: 4
batch_size: 16 #32
epochs: 100
epoch_size: 16000
val_show_number: 25
saved_model: 'saved_models/cyrillic.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: True
amp: True
optim: 'adamw' # default is Adadelta
lr: 0.5
sched_enabled: True
sched_MulLR_factor: 0.98
beta1: 0.9
rho: 0.9
eps: 0.00000001
grad_clip: 5
#Data processing
batch_max_length: 56
imgH: 64
imgW: 1200
rgb: False
contrast_adjust: False
sensitive: False
PAD: True
contrast_adjust: 0.0
data_filtering_off: True
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 512
hidden_size: 512
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
freeze_Prediction: False