number: '0123456789'
#symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ №"
symbol: ",-. "
#lang_char: 'abcdefghijklmnopqrstuvwxyzабвгдеёжзийклмнопрстуфхцчшщъыьэюя'
lang_char: 'абвгдеёжзийклмнопрстуфхцчшщъыьэюя'
experiment_name: 'ru_filtered'
train_data: 'all_data'
#valid_data: 'valid_data/ocr_doc_dataset_no_sts'
valid_data: 'valid_data/ocr_doc_dataset_test'
manualSeed: 1111
workers: 6
batch_size: 32 #32
num_iter: 10000
valInterval: 1000
saved_model: 'saved_models/resnet_ctc_doc_075.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: True
optim: False # default is Adadelta
lr: 0.01
beta1: 0.9
rho: 0.9
eps: 0.00000001
grad_clip: 5
#Data processing
select_data: 'ocr_doc_dataset_no_sts' # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 64
imgH: 96
imgW: 800
rgb: False
contrast_adjust: False
sensitive: False
PAD: True
contrast_adjust: 0.0
data_filtering_off: False
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'ResNet'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: True
freeze_SequenceModeling: False
freeze_Prediction: False