number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €₽"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ'
experiment_name: 'ru_orig_ft'
train_data: 'all_data'
valid_data: 'valid_data/ocr_doc_dataset_test'
manualSeed: 1111
workers: 12
batch_size: 32 #32
num_iter: 500000
valInterval: 5000
saved_model: 'saved_models/1101101.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: True
optim: 'adamw' # default is Adadelta
lr: 0.3
beta1: 0.9
rho: 0.9
eps: 0.00000001
grad_clip: 5
#Data processing
#select_data: 'text_dataset_ru_gray_10k3' # this is dataset folder in train_data
select_data: False # this is dataset folder in train_data
batch_ratio: '1' 
total_data_usage_ratio: 1.0
batch_max_length: 60
imgH: 64
imgW: 1200
rgb: False
contrast_adjust: False
sensitive: False
PAD: True
contrast_adjust: 0.0
data_filtering_off: True
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
freeze_Prediction: False