number: '0123456789'
symbol: "!\"#$%&'()*+,-./:;<=>?@[\\]^_`{|}~ €₽"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyzАБВГДЕЁЖЗИЙКЛМНОПРСТУФХЦЧШЩЪЫЬЭЮЯабвгдеёжзийклмнопрстуфхцчшщъыьэюяЂђЃѓЄєІіЇїЈјЉљЊњЋћЌќЎўЏџҐґҒғҚқҮүҲҳҶҷӀӏӢӣӨөӮӯ'
experiment_name: 'ru_orig_ft_new'
train_data: False
valid_items_count: 2000
valid_data: False
#Text generator options tg_*
tg_blur: 4
tg_random_blur: True
tg_words_len: 3
#tg_distributed: "172.25.0.86:50051"
tg_distributed: False
tg_augs:
  allow_list:
    - text_blur
    - text_noise
    - blur
    - motion_blur
    - sharpen
    - downsample
    - jpeg_artifact
    - sin_cos
  # number of simultanious augmentations
  k: 2
  # Image, Noise, Plain probabilities
  inp_weights:
    - 0.5
    - 0.40
    - 0.10
  text_blur: 4
  text_blur_rnd: True
  blur: 4
  blur_rnd: True
  downsample_factor: 4
  jpeg_artifact_q: 13
  motion_blur_sz_min: 10
  motion_blur_sz_max: 15
  invert_chance: 0.3
  overexposure_chance: 0.3
  overexposure_k: 1
manualSeed: 1111
workers: 12
batch_size: 64 #32
epochs: 50
epoch_size: 20000
val_show_number: 15
#saved_model: 'saved_models/cyrillic_g2.pth' #'saved_models/en_filtered/iter_300000.pth'
saved_model: 'saved_models/ru_orig_ft_new/79.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: True
amp: True
optim: 'adamw' # default is Adadelta
lr: 0.1
sched_enabled: True
sched_MulLR_factor: 0.95
beta1: 0.9
rho: 0.9
eps: 0.00000001
grad_clip: 5
#Data processing
batch_max_length: 56
imgH: 64
imgW: 1200
rgb: False
contrast_adjust: False
sensitive: False
PAD: True
contrast_adjust: 0.0
data_filtering_off: True
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
output_channel: 256
hidden_size: 256
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
freeze_Prediction: False