number: '0123456789'
symbol: "<"
lang_char: 'ABCDEFGHIJKLMNOPQRSTUVWXYZ'
experiment_name: 'vgg_none_attn_mrz'
train_data: False
valid_data: False
valid_items_count: 1000
status_every_batch: 25
#Text generator options tg_*
#tg_distributed: "172.25.0.86:50051"
tg_distributed: False
tg_dbg_server: False
tg_settings:
  filter_chars: "\n"
  generators:
    - mrz
  multiline: True
  length: 3
  augs:
    instances:
      i_blur1:
        type: "blur"
        opt:
          radius_min: 1.5
          radius_max: 2
      i_motion_blur1:
        type: "motion_blur"
        opt:
          size_min: 9
          size_max: 11
      i_downsample1:
        type: "downsample"
        opt:
          factor_min: 2
          factor_max: 4
      i_jpeg_artifact1:
        type: "jpeg_artifact"
        opt:
          quality_min: 8
          quality_max: 12
      i_jpeg_artifact_strong:
        type: "jpeg_artifact"
        opt:
          quality_min: 5
          quality_max: 7
      i_noise1:
        type: "noise"
        opt:
          mean: 1
          stddev_min: 0.1
          stddev_max: 0.3
          downsample_factor_min: 1
          downsample_factor_max: 4
          interpolation: "nearest"        
      i_noise_light1:
        type: "noise"
        opt:
          mean: 1
          stddev_min: 0.1
          stddev_max: 0.1
          downsample_factor_min: 1
          downsample_factor_max: 1
          interpolation: "nearest"
      i_sharpen1:
        type: "sharpen"
        opt:
          sharpness_min: 2
          sharpness_max: 40
      i_sin_cos1:
        type: "sin_cos"
        opt:
          max_offset: 0.35
      i_none1:
        type: "none"
      
    pipelines:
      main:
        type: "random_uniform"
        k: 1
        augs:
          # - i_downsample1
          #- blur_jpeg
          #- all_blurs
          #- i_noise1
          #- jp_sharp
          - i_none1
      blur_jpeg:
        type: "sequential"
        augs:
          - i_blur1
          - i_jpeg_artifact1
      all_blurs:
        type: "random_uniform"
        k: 1
        augs:
          - i_blur1
          - i_motion_blur1
      jp_sharp:
        type: "sequential"
        augs:
          - i_jpeg_artifact1
          - i_sharpen1

    # number of simultanious augmentations
    k: 1
    # Image, Noise, Plain probabilities
    inp_weights:
      - 0.0
      - 0.33
      - 0.33
    invert_chance: 0.0
    overexposure_chance: 0.0
    overexposure_k: 1
    blend_factor_min: 0.4
    blend_factor_max: 0.7
    font_color: 0
manualSeed: 1111
workers: 12
prefetch_train: 8
prefetch_valid: 24
batch_size: 16 #32
epochs: 40
epoch_size: 16000
val_show_number: 64
saved_model: '' #'saved_models/en_filtered/iter_300000.pth'
#saved_model: 'saved_models/vgg_none_attn_mrz/vgg_lstm_attn_ml_7.pth' #'saved_models/en_filtered/iter_300000.pth'
FT: False
amp: True
optim: 'adamw' # default is Adadelta
lr: 1
sched_enabled: True
sched_MulLR_factor: 1
beta1: 0.9
rho: 0.9
eps: 0.00000001
grad_clip: 5
#Data processing
batch_max_length: 100
imgH: 64
imgW: 1408
rgb: False
contrast_adjust: False
sensitive: False
PAD: True
contrast_adjust: 0.0
data_filtering_off: True
# Model Architecture
Transformation: 'None'
FeatureExtraction: 'VGG'
SequenceModeling: 'BiLSTM'
Prediction: 'CTC'
num_fiducial: 20
input_channel: 1
avg_pool_height: 2
output_channel: 512
hidden_size: 512
decode: 'greedy'
new_prediction: False
freeze_FeatureFxtraction: False
freeze_SequenceModeling: False
freeze_Prediction: False